### ISSUE TITLE
"Open Files" section doesn't have the same line height on some themes.

### ISSUE THREAD

**Issue by Goodwine** [oriolmirosa/open-files#3]
I'm using [silvestreh/atom-material-ui](https://github.com/atom-material/atom-material-ui) for my UI Theme, and there is a setting called "Compact tree view".
When using this plugin, I can see the Open Files pane above tree-view, but it has the default height instead of the compact height (and material-ui does take a lot of space if it's not compact).

If it's not possible to fix the panes, can we have a setting for custom height of the listed files?

Example of this happening, notice how the "open files" don't shrink like the tree-view files do.
![Example](http://i.imgur.com/GstGStP.gif)

**Comment by oriolmirosa** [comment]
Fixed with commit 6663fb71ac2348f8afe68b51355a7d6b0dc5a356. If this doesn't work properly, or if there are similar problems with other themes, please re-open the issue.
