### ISSUE TITLE
[FR] Allow "Open Files" panes to collapse

### ISSUE THREAD

**Issue by Goodwine** [oriolmirosa/open-files#4]
Very self explanatory, can the whole section collapse as if it was a directory?

**Comment by oriolmirosa** [comment]
I just implemented this feature with  6663fb71ac2348f8afe68b51355a7d6b0dc5a356. There is an option in the settings to toggle the feature in case the user does not want the panel to be collapseable and don't want to see the arrow that indicates if the panel is collapsed or not.
