### ISSUE TITLE
Open file order is alpha and doesn't match tab order

### ISSUE THREAD

**Issue by EmilVarona** [oriolmirosa/open-files#6]
Hi, I installed this today and expected the file list order to match the tab order (as it does in Sublime Text). The settings allow for a sort order options of base, ext and dir. How can I get this to list the files in the same order as the tabs?

**Comment by oriolmirosa** [comment]
At this point, open-files does not follow or affect the order of the tabs. The mechanism to sort the files in open-files, however, is taken directly from an Atom package called [tab-smart-sort](https://atom.io/packages/tab-smart-sort). If you install it and set the tab order to be the same as the files order in open-files, you will achieve what you want.
